# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token d82e0a2e70938d9f33116f9c522080a4bc846aff

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/22/
Content-Type: application/json
Authorization: Token d82e0a2e70938d9f33116f9c522080a4bc846aff

{
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 906743a40ef28ce9883a701c893db24e092760f9

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-10-01
Content-Type: application/json

###

# просмотреть список избранных
GET {{baseUrl}}/advertisements/favorites/
Content-Type: application/json
Authorization: Token 906743a40ef28ce9883a701c893db24e092760f9

###

# добавить в избранное
POST {{baseUrl}}/advertisements/favorites/
Content-Type: application/json
Authorization: Token 906743a40ef28ce9883a701c893db24e092760f9

{
  "favorite_id": "23"
}
###